### ISSUE TITLE
size_factor_normalize was not passed into  Run_DIRECT_NET function

### ISSUE THREAD

**Issue by biobai** [zhanglhbioinfor/DIRECT-NET#1]
pbmc <- Run_DIRECT_NET(pbmc, k_neigh = 50, atacbinary = TRUE, max_overlap=0.5, size_factor_normalize = FALSE, genome.info, focus_markers = c("GLB1","TAF1B"))
Error in Run_DIRECT_NET(pbmc, k_neigh = 50, atacbinary = TRUE, max_overlap = 0.5,  :
  unused argument (size_factor_normalize = FALSE)

**Comment by zhanglhbioinfor** [comment]
Thanks for pointing this out. We have updated the document.
